// <auto-generated />
namespace DoAnCoSo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DoAn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DoAn));
        
        string IMigrationMetadata.Id
        {
            get { return "202006011055161_DoAn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
